{
  "name": "𝗥𝗔𝗪𝗔𝗡𝗔-𝗠𝗗",
  "version": "1.0.0",
  "description": "WELCOME TO 𝗥𝗔𝗪𝗔𝗡𝗔-𝗠𝗗",
  "main": "start.js",
 "scripts": {
  "start": "pm2 start start.js --name '𝗥𝗔𝗪𝗔𝗡𝗔-𝗠𝗗' --deep-monitoring --attach",
  "stop": "pm2 stop 𝗥𝗔𝗪𝗔𝗡𝗔-𝗠𝗗",
  "restart": "pm2 restart 𝗥𝗔𝗪𝗔𝗡𝗔-𝗠𝗗"
} ,
  "dependencies": {
    "@whiskeysockets/baileys": "latest",
    "@adiwajshing/keyed-db": "latest",
    "pino": "latest",
    "pm2": "latest",
    "util": "latest",
    "express": "latest",
    "axios": "latest",
    "file_size_url": "latest",
    "fs-extra": "latest",
    "form-data": "latest",
    "fs": "0.0.1-security",
    "file-type": "latest",
    "crypto": "latest",
    "path": "latest",
    "node-fetch": "latest",
    "node-cache": "latest",
    "https": "latest",
    "megajs": "latest",
    "vm": "latest",
    "qrcode-terminal": "latest",
    "yt-search":"latest",
    "api-dylux":"latest",
    "fb-downloader-scrapper": "latest",
    "@vreden/youtube_scraper": "latest",
    "denethdev-ytmp3": "latest",
    "cheerio": "latest",
    "undici": "latest",
    "extract-zip": "latest",
    "moment-timezone": "latest",
    "mongoose":"latest"
  }
}
